Brewery.Web/Controllers/BrewsManagementController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Brewery.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Brewery.Web.Service;
using Brewery.Web.ViewModels;
using System.Collections.Generic;
using Brewery.Core.Constants;
using System;
using Brewery.Core.Interfaces.Services;

namespace Brewery.Web.Controllers
{
    [Authorize(Roles = AccountConstants.AdminRole)]
    public class BrewsManagementController : Controller
    {
        private readonly IMapper mapper;
        private readonly IBrewService brewService;
        private readonly IResourceService resourceService;
        private readonly IRecipeService recipeService;

        public BrewsManagementController(IBrewService brewService, IResourceService resourceService, IRecipeService recipeService, IMapper mapper)
        {
            this.resourceService = resourceService;
            this.brewService = brewService;
            this.mapper = mapper;
            this.recipeService = recipeService;
        }

        public async Task<IActionResult> Index()
        {
            List<BrewsViewModel> newBrewViewModel = new List<BrewsViewModel>();
            List<BrewModel> brews = await brewService.GetAllAsync();
            foreach (var brew in brews.Where(x => !x.IsRemoved))
            {
                newBrewViewModel.Add(mapper.BrewToBrewsViewModel(brew, true));
            }

            return View(newBrewViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var resources = await resourceService.GetAllAsync();
            List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> resourcesSelect = resources.Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Value = x.Unit, Text = x.Name }).ToList();
            var brew = new BrewsViewModel()
            {
                IsNew = true,
                ShowAlert = false,
                ResoucesSelect = resourcesSelect,
            };
            brew.Recipes.Add(new RecipeModel() { IsNew = true });
            return View(brew);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrewsViewModel brew)
        {
            if (brew == null)
            {
                NotFound();
            }

            string name = brew.Name;
            brew.IsNew = true;
            brew.IsValid = false;
            if (!ModelState.IsValid)
            {
                return View(brew);
            }

            if (!ValidateBrew(brew) || !await brewService.FindIfNameIsUniqueAsync(name))
            {
                return View(brew);
            }
            else
            {
                BrewModel newBrew = mapper.BrewsViewModelToBrew(brew);
                newBrew.Recipes = brew.Recipes;
                brewService.AddBrewAndRecipesAsync(newBrew);
                brew.IsValid = true;
                return RedirectToAction(RoutingConstants.BrewsManagementIndex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var brew = await GetMappedBrewViewModel(id);
            return View(brew);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BrewsViewModel brew)
        {
            if (!ModelState.IsValid && !ValidateBrew(brew))
            {
                brew.IsValid = false;
                return View(brew);
            }
            else
            {
                BrewModel updatedBrew = brewService.Update(mapper.BrewsViewModelToBrew(brew));
                if (updatedBrew == null)
                {
                    NotFound();
                }
                else
                {
                    await recipeService.AddOrUpdateAsync(brew.Recipes, brew.BrewId);
                }

                brew.IsValid = true;
            }

            if (brew.IsValid.Value)
            {
                return RedirectToAction(RoutingConstants.BrewsManagementIndex);
            }
            else
            {
                return View(brew);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid id)
        {
            if (Guid.Empty == id)
            {
                return NotFound();
            }

            bool result = brewService.FindIfExistsAsync(id).ConfigureAwait(false).GetAwaiter().GetResult();
            if (result)
            {
                brewService.Delete(id);
            }

            return Json(new
            {
                success = result,
                data = id
            });
        }

        [HttpPost]
        public IActionResult GetOptions(Guid id, string[] resources)
        {
            List<ResourceModel> models = new List<ResourceModel>();
            if (resources != null && resources.Any())
            {
                models = resourceService.GetAllAsync(resources).Result.ToList();
            }

            return Json(new
            {
                success = true,
                data = models
            });
        }

        #region Private Methods
        private bool ValidateBrew(BrewsViewModel brew)
        {
            return brew != null && !string.IsNullOrEmpty(brew.Name)
                && brew.Name.Trim().Length < NumericConstants.BrewNameMaxLength
                && (!string.IsNullOrEmpty(brew.Description));
        }

        private async Task<BrewsViewModel> GetMappedBrewViewModel(Guid id)
        {
            var resources = await resourceService.GetAllAsync();
            BrewModel brewModel = await brewService.GetByIdAsync(id, true);
            BrewsViewModel brew = mapper.BrewToBrewsViewModel(brewModel, false);

            foreach (var recipe in brewModel.Recipes)
            {
                brew.Recipes.Add(new RecipeModel() { Amount = recipe.Amount, Unit = recipe.Resource.Unit, IsNew = false, ResourceName = recipe.Resource.Name, Description = recipe.Description });
            }

            brew.ResoucesSelect = resources.Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Value = x.Unit, Text = x.Name }).ToList();

            if (!brew.Recipes.Any())
            {
                brew.Recipes.Add(new RecipeModel() { Unit = resources.FirstOrDefault().Unit, IsNew = true, ResourceName = resources.FirstOrDefault().Name });
            }

            return brew;
        }
        #endregion
    }
}

Brewery.Web/Controllers/ProducedGoodsController.cs
using Brewery.Core.Interfaces.Services;
using Brewery.Core.Models;
using Brewery.Web.Service;
using Brewery.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Brewery.Web.Controllers
{
    public class ProducedGoodsController : Controller
    {
        private readonly IProducedGoodsService producedGoodsService;
        private readonly IBrewService brewService;
        private readonly IResourceService resourceService;
        private readonly IRecipeService recipeService;
        private readonly IMapper mapper;

        public ProducedGoodsController(IProducedGoodsService producedGoodsService,
            IBrewService brewService,
            IResourceService resourceService,
            IRecipeService recipeService,
            IMapper mapper)
        {
            this.mapper = mapper;
            this.producedGoodsService = producedGoodsService;
            this.brewService = brewService;
            this.resourceService = resourceService;
            this.recipeService = recipeService;
        }

        public IActionResult Index()
        {
            List<ProducedModel> producedModels = producedGoodsService.GetProducedGoods();
            List<ProducedGoodsViewModel> producedGoodsViewModel = mapper.ProducedModelToProducedGoodsViewModel(producedModels);
            return View(producedGoodsViewModel);
        }

        public async Task<IActionResult> Create(Guid id, int amount)
        {
            bool success = false;
            if (Guid.Empty == id)
            {
          
                throw new ArgumentNullException();
            }

            BrewModel brew = await brewService.GetByIdAsync(id, true);
            if (brew == null)
            {
           
                throw new ArgumentNullException();
            }

            ResourceModel model = new ResourceModel();
            if (amount > 0)
            {
                foreach (var recipe in brew.Recipes)
                {
                    ResourceModel resource = await resourceService.GetByIdAsync(recipe.ResourceId);
                    resource.AmountInStock -= (amount * (int)recipe.Amount);

                    if (model != null)
                    {
                        model = resourceService.UpdateResourceAmount(resource.ResourceId, resource.AmountInStock);
                    }
                }

                if (model != null)
                {
                    DateTime today = DateTime.Today;
                    ProducedModel producedModel = new ProducedModel()
                    {
                        Amount = amount,
                        BrewId = brew.BrewId,
                        CreateDate = today.Date,
                        ExprireDate = today.AddMonths(6)
                    };

                    ProducedModel produced = await producedGoodsService.InsertAsync(producedModel);
                    success = produced != null;
                }
                else
                {
                    throw new ArgumentNullException(nameof(model));
                }
            }
            ProducedModel[] producedModels = producedGoodsService.GetProducedGoods().ToArray();

            return Json(new
            {
                success = success,
                producedGoods = producedModels
            });
        }
    }
}

Brewery.Web/Controllers/ResourceManagerController.cs
using Brewery.Web.Service;
using Brewery.Web.ViewModels;
using Brewery.Core.Constants;
using Brewery.Core.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System;
using Brewery.Core.Interfaces.Services;

namespace Brewery.Web.Controllers
{
    [Authorize(Roles = AccountConstants.AdminRole)]
    public class ResourceManagerController : Controller
    {
        private readonly IMapper mapper;
        private readonly IResourceService resourceService;

        public ResourceManagerController(IResourceService resourceService, IMapper mapper)
        {
            this.resourceService = resourceService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            List<ResourceViewModel> resources = new List<ResourceViewModel>();
            var resourceModels = await resourceService.GetAllAsync();
            resources = resourceModels.Where(x => !x.IsRemoved).Select(x => mapper.ResourceToResourceViewModel(x)).ToList();
            return View(resources);
        }

        public IActionResult Create()
        {
            ResourceViewModel resource = new ResourceViewModel();
            resource.IsNew = true;
            return View(resource);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ResourceViewModel resource)
        {
            bool isValid = resource.IsValid.Value;
            if (isValid && ModelState.IsValid)
            {
                await resourceService.InsertAsync(mapper.ResourceViewModelToResource(resource));
                return RedirectToAction(nameof(Index));
            }
            else
            {
                resource.IsValid = false;
                return View(resource);
            }
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            if (Guid.Empty == id)
            {
                return NotFound();
            }

            var resource = await resourceService.GetByIdAsync(id);
            if (resource == null)
            {
                return NotFound();
            }

            return View(mapper.ResourceToResourceViewModel(resource));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ResourceViewModel resource)
        {
            resource.IsValid = ModelState.IsValid || resource == null || string.IsNullOrEmpty(resource.Name) || Guid.Empty == resource.Id;
            bool isNameUnique = await resourceService.FindIfNameIsUniqueAsync(resource.Id, resource.Name);
            if (!resource.IsValid.Value && !isNameUnique)
            {
                return View(resource);
            }

            ResourceModel editedResource = new ResourceModel();
            editedResource = resourceService.Update(mapper.ResourceViewModelToResource(resource));
            if (!ResourceExists(resource.Id))
            {
                return NotFound();
            }

            if (editedResource == null)
            {
                return NotFound();
            }

            ResourceViewModel newResourceViewModel = mapper.ResourceToResourceViewModel(editedResource);
            newResourceViewModel.ShowAlert = true;
            return View(newResourceViewModel);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            if (Guid.Empty == id)
            {
                NotFound();
            }

            bool result = await resourceService.DeleteAsync(id);

            return Json(new
            {
                success = result,
            });
        }

        #region Private Methods
        private bool ResourceExists(Guid id)
        {
            return resourceService.GetByIdAsync(id) != null;
        }
        #endregion
    }
}

Brewery.Web/Views/Shared/_EditResource.cshtml
@model Brewery.Web.ViewModels.BrewsViewModel

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label"></label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description" class="text-danger"></span>
</div>

Brewery.Web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Index</a></li>
                <li><a asp-area="" asp-controller="ResourceManager" asp-action="Index">Resource Management</a></li>
                <li><a asp-area="" asp-controller="BrewsManagement" asp-action="Index">Brews Management</a></li>
                <li><a asp-area="" asp-controller="ProducedGoods" asp-action="Index">Produced Goods</a></li>
            </ul>
            <partial name="_LoginPartial" />
        </div
    </div>
</nav>

Brewery.Web/Views/Shared/_LandingLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">



    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    @RenderSection("Styles", required: false)
</head>
<body>
    <div>
        @Html.Partial("_Header")
        @RenderBody()
    </div>
</body>
</html>

@RenderSection("Scripts", required: false)

Brewery.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IHostingEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Brewery.Web</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/Identity/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/Identity/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/" class="navbar-brand">Brewery.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                @{
                    var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                }
                @if (result.Success)
                {
                    await Html.RenderPartialAsync("_LoginPartial");
                }
                else
                {
                    throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                        "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                        $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Brewery.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/Identity/lib/jquery/dist/jquery.js"></script>
        <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/Identity/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/Identity/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/Identity/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>